version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      # - "traefik.http.routers.nginx.rule=Host(`nginx.idmu.ml`)"
      # - "traefik.http.services.nginx.loadbalancer.server.port=80"

networks:
  traefik:
    external: true
